### ISSUE TITLE
Wrong protocol for p2p port? TCP instead of UDP

### ISSUE THREAD

**Issue by pico-prob** [dappnode/DAppNodePackage-prysm-beacon-chain#6]
I am having trouble to get my test validator running (not connecting p2p). Configuring my firewall, I stumbled over the [prysm doc](https://docs.prylabs.network/docs/prysm-usage/p2p-host-ip#port-forwarding):

It requires a `TCP` and a `UDP` port. In the installed version (`1.0.3 (v1.0.0-alpha.16 upstream)`) the config offers only two ports with correct portnumber, however with port `12000` running (wrongly) as `TCP`. I crosschecked for the docker container: 

```
DAppNodePackage-prysm-altona-beacon-chain.dnp.dappnode.eth   Up 9 minutes        0.0.0.0:12000->12000/tcp, 0.0.0.0:13000->13000/tcp
```

The Altona package UI references to this repo

**Comment by dapplion** [comment]
Please use our latest Prysm packages 
- https://github.com/dappnode/DAppNodePackage-prysm
- https://github.com/dappnode/DAppNodePackage-prysm-pyrmont
